services:
  - type: web
    name: techies-app
    env: node
    plan: free
    buildCommand: npm install -g bower && npm install && bower install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: SESSION_SECRET
        generateValue: true 